id: I879E4DEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:27:19+00:00'
last_modified: '2022-06-08T10:57:42.415209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ65025
  title: དྲན་པ་བཀའ་ཐང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8444':
      image_group_id: I4CZ65637
      title: ''
      total_pages: 527
      order: 1
      base_file: 8444.txt
    4AA9:
      image_group_id: I4CZ65638
      title: ''
      total_pages: 437
      order: 2
      base_file: 4AA9.txt
    855B:
      image_group_id: I4CZ65639
      title: ''
      total_pages: 436
      order: 3
      base_file: 855B.txt
    '4977':
      image_group_id: I4CZ65640
      title: ''
      total_pages: 429
      order: 4
      base_file: 4977.txt
    CCCA:
      image_group_id: I4CZ65641
      title: ''
      total_pages: 419
      order: 5
      base_file: CCCA.txt
    8BD3:
      image_group_id: I4CZ65642
      title: ''
      total_pages: 409
      order: 6
      base_file: 8BD3.txt
    '4408':
      image_group_id: I4CZ65643
      title: ''
      total_pages: 472
      order: 7
      base_file: 4408.txt
    FC4C:
      image_group_id: I4CZ65644
      title: ''
      total_pages: 398
      order: 8
      base_file: FC4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
