id: I879E4DEE
legacy_id: P009427
ocr_import_info:
  bdrc_scan_id: W4CZ65025
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T01:24:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:53:30.808641+00:00'
last_modified: 2022-09-04 04:54:46.682430
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ65025
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ65025
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲན་པ་བཀའ་ཐང་།
  author: གཡུང་དྲུང་དབང་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.5761021999906153
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I4CZ65637:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65637
      total_pages: 527
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ65637.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5846000979565837
    legacy_id: v001
  I4CZ65643:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65643
      total_pages: 472
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4CZ65643.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5590227788878209
    legacy_id: v007
  I4CZ65639:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65639
      total_pages: 436
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4CZ65639.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.5999495765134255
    legacy_id: v003
  I4CZ65641:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65641
      total_pages: 419
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4CZ65641.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.5898012334606343
    legacy_id: v005
  I4CZ65642:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65642
      total_pages: 409
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4CZ65642.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5565304132057195
    legacy_id: v006
  I4CZ65638:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65638
      total_pages: 437
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4CZ65638.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6199436033422691
    legacy_id: v002
  I4CZ65640:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65640
      total_pages: 429
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4CZ65640.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5439693589508533
    legacy_id: v004
  I4CZ65644:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65644
      total_pages: 398
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4CZ65644.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5583206689022642
    legacy_id: v008
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
